export const APP_NAME: string = 'HR';

export const MODAL_BODY_TYPES: { [key: string]: string } = Object.freeze({
    DEFAULT: "DEFAULT",
    LEAD_ADD_NEW: "LEAD_ADD_NEW",
    TASK_ADD_NEW: "TASK_ADD_NEW",
    USER_ADD_NEW: "USER_ADD_NEW",
    ROLE_ADD_NEW: "ROLE_ADD_NEW",
    AREA_ADD_NEW: "AREA_ADD_NEW",
    DOCUMENTATION_ADD_NEW: "DOCUMENTATION_ADD_NEW",
    PROJECT_ADD_NEW: "PROJECT_ADD_NEW",
    AREA_EDIT: "AREA_EDIT",
    PERMISSION_ADD_NEW: "PERMISSION_ADD_NEW",
    PERMISSION_EDIT: "PERMISSION_EDIT",
    PROJECT_EDIT: "PROJECT_EDIT",
    DOCUMENTATION_EDIT: "DOCUMENTATION_EDIT",
    ROLE_EDIT: "ROLE_EDIT",
    USER_EDIT: "USER_EDIT",
    TASK_DELETE: "TASK_DELETE",
    LEAD_DELETE: "LEAD_DELETE",
    USER_DELETE: "USER_DELETE",
    PERMISSION_DELETE: "PERMISSION_DELETE",
    ROLE_DELETE: "ROLE_DELETE",
    AREA_DELETE: "AREA_DELETE",
    PROJECT_DELETE: "PROJECT_DELETE",
    DOCUMENTATION_DELETE: "DOCUMENTATION_DELETE",

});


export const RIGHT_DRAWER_TYPES: { [key: string]: string } = Object.freeze({
    DEFAULT: "DEFAULT",
    NOTIFICATION: "NOTIFICATION",
});

export const CONFIRMATION_MODAL_CLOSE_TYPES: { [key: string]: string } = Object.freeze({
    DEFAULT: "DEFAULT",
    TASK_DELETE: "TASK_DELETE",
    ROLE_DELETE: "ROLE_DELETE",
    PERMISSION_DELETE: "PERMISSION_DELETE",
    USER_DELETE: "USER_DELETE",
    AREA_DELETE: "AREA_DELETE",
    PROJECT_DELETE: "PROJECT_DELETE",
    DOCUMENTATION_DELETE: "DOCUMENTATION_DELETE",
});



export const FILTER_BODY_TYPES: { [key: string]: string } = Object.freeze({
    DEFAULT: "DEFAULT",
    FILTER_TASK: "FILTER_TASK",

});